---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/e2e-world-organisation/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-main-awgh
