apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/jsztuka/integration-service/config/default?ref=1136ee400a7cabfd303d89f0f24e6968f40c23fd
  - https://github.com/jsztuka/integration-service/config/snapshotgc?ref=1136ee400a7cabfd303d89f0f24e6968f40c23fd
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/jsztuka/integration-service
    newTag: v577.6
configMapGenerator:
  - name: console-url
    literals:
      - CONSOLE_URL=""
namespace: integration-service
patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector
components:
  - ../rh-certs
