resources:
- https://github.com/redhat-appstudio/jvm-build-service/deploy/kcp?ref=444b759a3ce9a4a4aa323a82dfd13aaad71fb42f

patchesStrategicMerge:
- self-binding.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: IMAGE_TAG
          value: 444b759a3ce9a4a4aa323a82dfd13aaad71fb42f
    target:
      kind: Deployment
      name: hacbs-jvm-operator

images:
- name: hacbs-jvm-operator
  newName: quay.io/redhat-appstudio/hacbs-jvm-controller
  newTag: 444b759a3ce9a4a4aa323a82dfd13aaad71fb42f

namespace: jvm-build-service

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Skip applying the jvmbuildservice operands while the jvm-build-service operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
