apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: has-export
spec:
  permissionClaims:
    - group: ""
      resource: "secrets"
    - group: ""
      resource: "namespaces"
    - group: ""
      resource: "configmaps"
    - identityHash: application-api
      group: "appstudio.redhat.com"
      resource: "applications"
    - identityHash: application-api
      group: "appstudio.redhat.com"
      resource: "applicationsnapshotenvironmentbindings"
    - identityHash: application-api
      group: "appstudio.redhat.com"
      resource: "components"
    - identityHash: application-api
      group: "appstudio.redhat.com"
      resource: "componentdetectionqueries"
    - identityHash: application-api
      group: "appstudio.redhat.com"
      resource: "environments"
    - identityHash: 0595fa2ebb8e3c1ee5a3a1a1709006b9664db26532080185d59d5929dacf7a80
      group: "appstudio.redhat.com"
      resource: "spiaccesstokens"
    - identityHash: 0595fa2ebb8e3c1ee5a3a1a1709006b9664db26532080185d59d5929dacf7a80
      group: "appstudio.redhat.com"
      resource: "spiaccesstokenbindings"