kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: has-olm-pruner
rules:
  - verbs:
      - list
      - get
      - delete
      - update
      - patch
    apiGroups:
      - 'operators.coreos.com/v1alpha1'
    resources:
      - ClusterServiceVersion
      - Subscription
      - CatalogSource
  - verbs:
      - list
      - get
      - delete
      - update
      - patch
    apiGroups:
      - 'operators.coreos.com/v1'
    resources:
      - OperatorGroup
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: has-olm-pruner-rolebinding
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: johnmcollier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: has-olm-pruner

